[app]
host = "0.0.0.0"
version = "0.0.0"
port = 8080

[postgres]
host = "localhost"
port = 5432
name = "postgres"
user = "user"
password = "password"
max_connections = 10

[logging]
level = "debug"
format = "pretty"
